services:
  proxy:
    container_name: proxy
    image: nginx:alpine3.18-slim
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./static-files:/usr/share/nginx/html
      - ${CERT_PATH}:/etc/ssl/certs/${HOST}
    ports:
      - 80:80
      - 443:443

  app:
    container_name: app
    build:
      context: ./app
    volumes:
      - ./app/src:/app/src
